/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.freedomotic.knx;

import java.util.Collection;
import java.util.Iterator;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tuwien.auto.calimero.datapoint.Datapoint;
import tuwien.auto.calimero.datapoint.DatapointMap;

/**
 *
 * @author mauro
 */
public class KnxFrame extends javax.swing.JFrame {

    Knx pluginReference;

    /**
     * Creates new form KnxGui
     */
    public KnxFrame(Knx pluginReference) {
        this.pluginReference = pluginReference;
      //  DatapointMap m = Knx.LoadDatapoints(pluginReference.dataPointsFile);
        
        initComponents();
      //  DisplayData(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayData(DatapointMap m) {




        /*
         * Collection c = ((DatapointMap) m).getDatapoints(); DefaultTableModel
         * aModel = new DefaultTableModel(); if (!c.isEmpty()) {
         *
         * //setting the column name //Object[] tableColumnNames = new
         * Object[2]; //tableColumnNames[0] = "Datapoint Name";
         * //tableColumnNames[1] = "Knx Address";
         * //aModel.setColumnIdentifiers(tableColumnNames); if (c == null) {
         * this.tbDatapoints.setModel(aModel); return; }
         *
         * Object[] objects = new Object[2]; Iterator<Datapoint> iterator =
         * c.iterator(); //populating the tablemodel while (iterator.hasNext())
         * { objects[0] = iterator.next().getName(); objects[1] =
         * iterator.next().getMainAddress();
         *
         * tbDatapoints.; }
         *
         * //binding the jtable to the model
         * //this.tbDatapoints.setModel(aModel); } else { System.out.println("C
         * é vuota");
         *
         */

        //JPanel panel = new JPanel();
        String data[][] = {{"Vinod", "100"}, {"Raju", "200"}, {"Ranju", "300"}};
        String col[] = {"Name", "code"};
        DefaultTableModel model = new DefaultTableModel(data, col);
        JTable table = new JTable(model);
        //Insert first position
        model.insertRow(0, new Object[]{"Ranjan", "50"});
        //Insert 4 position
        model.insertRow(3, new Object[]{"Amar", "600"});
        //Insert last position
        model.insertRow(table.getRowCount(), new Object[]{"Sushil", "600"});
        this.add(table);
        //this.add(panel);
        //panel.setVisible(true);
        table.setVisible(true);
        
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
